### ISSUE TITLE
Stuck in Map if table is broken

### ISSUE THREAD

**Issue by xXRhaenyraXx** [nbusseneau/BetterCartographyTable#13] opened 2024-07-16 18:53 UTC
Hello,

If the table is broken while you are viewing the map, you get stuck in the map screen and have no choice but to alt f4 (and hope that someone can save for you before you do)

**Comment by nbusseneau** [comment] 2024-07-19 00:46
Haha, nice catch. This should be fixed by 7d8dfdcd5bd547cef480dc1fe723c7b466378f40, released in [0.5.10](https://github.com/nbusseneau/BetterCartographyTable/releases/tag/0.5.10).

**Comment by xXRhaenyraXx** [comment] 2024-07-20 02:57
Hi, still broken. Just tested with my admin team :)

**Comment by nbusseneau** [comment] 2024-07-20 10:40
I can't reproduce this anymore with latest version, can you give your reproduction steps? A minimal isolated setup would be even better.

**Comment by nbusseneau** [comment] 2024-07-20 21:32
Is this also fixed after update? @xXRhaenyraXx

**Closed as completed** 2024-07-23 11:50 UTC
Labels: bug
