### ISSUE TITLE
Mod Conflict with EpicLoot Bounty/TreaureMap pins created by the Merchant on accepting Bounties/TreasureMaps

### ISSUE THREAD

**Issue by Jester2020** [nbusseneau/BetterCartographyTable#4] opened 2024-03-11 10:37 UTC
When installed with EpicLoot the Icon and Name strings are hidden from the Bounty/TreasureMap Indicators on the map. It doesn't break the actual Bounty or Treaure Map just the map feature.

![EpicLoot_MissingBounty Treasure_Icon Text](https://github.com/nbusseneau/BetterCartographyTable/assets/105181072/99e3aecc-9914-46f0-8d00-3a0af1267c60)

![EpicLoot_WorkingBounty_IconandName](https://github.com/nbusseneau/BetterCartographyTable/assets/105181072/8dacb156-4880-4ef3-b26a-9e22be9d562f)

**Comment by OrianaVenture** [comment] 2024-03-25 16:16
Confirmed the issue is happening on Epic Loot version 0.9.37 and Better Cartography Table version 0.2.0. If you need assistance with fixing mod compatibility please reach out to me as I am currently helping maintain Epic Loot.

**Comment by nbusseneau** [comment] 2024-03-25 23:50
@OrianaVenture Thanks! I will have some time to look into this over the next week. I don't personally use Epic Loot, any tips on how to easily trigger / reproduce this situation?

**Comment by Jester2020** [comment] 2024-03-26 01:54
Hi, you will have to locate the merchant first. Then accept a bounty or buy a treasure map. It's consistent every time. You only need to install EpicLoot (turn on adventure mode) and your mod.

**Comment by Jester2020** [comment] 2024-05-10 07:49
any chance we'll see a fix for this? thanks

**Comment by nbusseneau** [comment] 2024-05-10 21:50
Yeah I actually started changing how stuff works internally so that's it's less likely that it clashes with other mods (including this specific case here), however I don't have any ETA to give because I'm currently quite busy dealing with stuff happening over at the Hades II modding scene now that the game came out😅

**Comment by Jester2020** [comment] 2024-05-11 04:37
No worries, probably doesn't make sense to finalize the changes until they're verified against the Ashlands release. have fun with Hades II :D

**Comment by nbusseneau** [comment] 2024-05-29 04:11
This should be fixed in version [0.4.0](https://github.com/nbusseneau/BetterCartographyTable/releases/tag/0.4.0).

**Closed as completed by nbusseneau** 2024-05-29 04:11 UTC
Labels: enhancement
