### ISSUE TITLE
Unable to see other players on map

### ISSUE THREAD

**Issue by Nundeska** [nbusseneau/BetterCartographyTable#1] opened 2024-02-17 22:14 UTC
Good day!

I have been looking for a cartography table mod for Valheim, and I absolutely love the functions of your mod. I have however noticed that unfortunately when your mod is installed it doesn't display other players on the map. I don't know if this is an intended feature, but has proved troublesome when playing some friends, and making it impossible for me to know where anyone is located at any given time. Thank you again for this mod, I absolutely love the function it adds to the cartography table.

**Comment by nbusseneau** [comment] 2024-02-18 19:47
Hello, thanks for the kind words! I can't reproduce the issue on my end and players' position seem to display just fine... Do you happen to have others mods installed that could lead to conflicts?

**Comment by Nundeska** [comment] 2024-02-18 20:43
It is definitely possible that a mod interaction could be causing the issue. I'm not sure on my end which it could be, that would take a long time of disabling and reenabling one at a time lol.

I initially thought this was an issue directly with the mod as when I disabled it and relaunched I was able to open my map away from the cartography table and see fellow players just fine.

If you would like I can send you a screenshot of the issue in game, and a list of mods I am using, and maybe that would help understand a possible interaction issue between mods?

**Comment by nbusseneau** [comment] 2024-02-18 20:48
Yes please. FYI you can copy/paste a list of your mods when using r2modman via `Settings` > `Modpacks` > `Show dependency strings`.

**Comment by Nundeska** [comment] 2024-02-18 20:51
The mods I am using: denikson-BepInExPack_Valheim-5.4.2202
Advize-PlantEverything-1.16.2
Marf-FuelEternal-1.2.1
Advize-PlantEasily-1.7.2
Azumatt-Build_Camera_Custom_Hammers_Edition-1.2.2
MaxiMods-MultiCraft-1.3.0
Smoothbrain-DualWield-1.0.9
Azumatt-Official_BepInEx_ConfigurationManager-18.2.0
blacks7ar-SNEAKer-1.1.3
OdinPlus-BetterLanterns-1.0.7
Smoothbrain-FoodCustomizer-1.0.4
Vapok-AutoFeedRedux-1.0.3
ComfyMods-Gizmo-1.9.0
JereKuusela-Server_devcommands-1.74.0
Azumatt-AzuExtendedPlayerInventory-1.3.12
nbusseneau-Better_Cartography_Table-0.1.0

And I have also attached a screenshot, I pinged where my friend should be standing on the map, but his name: Teets, is in the middle of the ocean.

![20240218154908_1](https://github.com/nbusseneau/BetterCartographyTable/assets/160362939/3da8d9bc-88fb-4278-819f-478eca725b0e)

**Comment by Nundeska** [comment] 2024-02-18 20:53
I have also noticed it is hit or miss with players, as some people it will have no issue keeping their map placement up to date, and others it will do as it is doing for my friend Teets

**Comment by nbusseneau** [comment] 2024-02-18 20:56
Huh. I have no idea what's happening. At a glance, none of the other mods you have seem to interact with the map, so I don't see any incompatibility. At the same time, I still have no idea why it does not work on your end, especially only for *some* players, as my mod is not supposed to change anything related to player pins.

Are the persons you're not receiving the position from also using the same mods as you are?

**Comment by Nundeska** [comment] 2024-02-18 20:59
We are on a dedicated server that I admin, and have added all the mods listed above to the server files directly, and we all also use the same list client side as well, so as to not cause any issues. I haven't had everyone install your cartography table mod yet as of the issue I have been having, is it possible this is just a weird interaction where everyone needs to have the mod installed collectively?

**Comment by nbusseneau** [comment] 2024-02-18 21:00
I don't know. It's weird to me that only some of the players present an issue and some do not. You could always try to have Teets install it and see if the issue persists, it's worth a shot. I'm currently looking over the code once again to figure out if I missed something.

**Comment by nbusseneau** [comment] 2024-02-25 18:55
FWIW I did review the logic for player positions and I still can't figure out a reason why the mod would impact anything... :/ Very strange issue.

**Comment by Seppel33** [comment] 2024-03-12 16:30
Just wanted to say I have the same problem. If one other person is on the server I can see them on the map. If more are online, I can always only see one, the others are floating names like in the screenshot.
Other mods we use on the server:
BuildRestrictionTweaksSync
AdvancedTerrainModifiers
Digitalroots_Slope_Combat_Assistance
Eternal Fire

**Comment by nbusseneau** [comment] 2024-05-29 04:11
This should be fixed in version [0.4.0](https://github.com/nbusseneau/BetterCartographyTable/releases/tag/0.4.0).

**Closed as completed by nbusseneau** 2024-05-29 04:11 UTC
Labels: bug
